backend:
  name: github
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: Home
        name: home
        file: src/admin/content/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Datum, name: date, widget: date, format: DD. MMMM YYYY }
          - {
              label: Hintergrundbild,
              name: background,
              widget: image,
              allow_multiple: false,
            }
          - { label: Apéro Passwort, name: apero_pw, widget: string }
          - { label: Fest Passwort, name: fest_pw, widget: string }
      - label: "Anmeldung Apéro"
        name: "rsvp"
        file: "src/admin/content/rsvp_apero.md"
        fields:
          - { label: Apero Anmeldung Intro, name: body, widget: markdown }
      - label: "Anmeldung Fest"
        name: "rsvp_fest"
        file: src/admin/content/rsvp_fest.md
        fields:
          - { label: Fest Anmeldung Intro, name: body, widget: markdown }
      - label: "Anmeldung Bestätigung und Danke"
        name: "rsvp_thx"
        file: src/admin/content/rsvp_thx.md
        fields:
          - { label: Text - Danke fürs ausfüllen, name: body, widget: markdown }

  - name: gallery
    label: Galerie
    folder: src/admin/content/gallery
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - { label: Name, name: title, widget: string }
      - { label: Bilder, name: images, widget: image, allow_multiple: true }
