backend:
  name: git-gateway
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: Home
        name: home
        file: src/admin/content/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Datum, name: date, widget: string }
          - { label: Code Platzhalter, name: code, widget: string }
          - {
              label: Hintergrundbild,
              name: background,
              widget: image,
              allow_multiple: false,
            }
          - { label: Apéro Passwort, name: apero_pw, widget: string }
          - { label: Fest Passwort, name: fest_pw, widget: string }
      - label: Info
        name: info
        file: src/admin/content/info.md
        fields:
          - { label: Infos, name: body, widget: markdown }
      - label: Meta Infos
        name: meta
        file: src/admin/content/meta.md
        fields:
          - { label: Titel (Browsertab), name: title, widget: string }
          - {
              label: Beschrieb (Beim teilen auf WhatsApp z.B.),
              description: Beschrieb beim Teilen der Seite z.B. auf Facebook oder WhatsApp,
              name: description,
              widget: string,
            }
          - {
              label: Titelbild (Beim teilen auf WhatsApp z.B.),
              description: Bild beim Teilen des Links auf WhatsApp oder Facebook,
              name: img,
              widget: image,
            }
      - label: "Anmeldung Apéro"
        name: "rsvp"
        file: "src/admin/content/rsvp_apero.md"
        fields:
          - { label: Apero Anmeldung Intro, name: body, widget: markdown }
          - { label: Vorname, name: firstname, widget: string }
          - { label: Vorname Fehler, name: firstname_error, widget: string }
          - { label: Nachname, name: lastname, widget: string }
          - { label: Nachname Fehler, name: lastname_error, widget: string }
          - { label: Erwachsene, name: adults, widget: string }
          - { label: Erwachsene Fehler, name: adults_error, widget: string }
          - { label: Kinder, name: children, widget: string }
          - { label: Kinder Fehler, name: children_error, widget: string }
          - { label: Bemerkungen, name: comments, widget: string }
      - label: "Anmeldung Fest"
        name: "rsvp_fest"
        file: src/admin/content/rsvp_fest.md
        fields:
          - { label: Fest Anmeldung Intro, name: body, widget: markdown }
          - { label: Vorname, name: firstname, widget: string }
          - { label: Vorname Fehler, name: firstname_error, widget: string }
          - { label: Nachname, name: lastname, widget: string }
          - { label: Nachname Fehler, name: lastname_error, widget: string }
          - { label: Apéro, name: apero, widget: string }
          - { label: Apéro Fehler, name: apero_error, widget: string }
          - { label: Abendessen, name: fest, widget: string }
          - { label: Abendessen Fehler, name: fest_error, widget: string }
          - { label: Übernachtung, name: night, widget: string }
          - { label: Übernachtung Fehler, name: night_error, widget: string }
          - { label: Bemerkungen, name: comments, widget: string }
          - { label: Gast hinzufügen, name: add_person, widget: string }
      - label: "Anmeldung Bestätigung und Danke"
        name: "rsvp_thx"
        file: src/admin/content/rsvp_thx.md
        fields:
          - { label: Text - Danke fürs ausfüllen, name: body, widget: markdown }
          - { label: Weitere Anmeldung, name: add_invite, widget: string }
      - label: Programm Apero
        name: program_apero
        file: src/admin/content/program_apero.md
        fields:
          - { label: Programm Apero, name: body, widget: markdown }
      - label: Programm Fest
        name: program_fest
        file: src/admin/content/program_fest.md
        fields:
          - { label: Programm Fest, name: body, widget: markdown }
      - label: Anfahrt
        name: map
        file: src/admin/content/map.md
        fields:
          - { label: Anfahrt, name: body, widget: markdown }
          - { label: Auf Maps anzeigen, name: show_on_maps, widget: string }
      - label: Fussnote
        name: footer
        file: src/admin/content/footer.md
        fields:
          - { label: Impressum, name: body, widget: markdown }
          - { label: Passwort zurücksetzen, name: reset_pw, widget: string }

  - name: gallery
    label: Galerie
    folder: src/admin/content/gallery
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - { label: Seitenname, name: pagename, widget: string }
      - { label: Name, name: title, widget: string }
      - {
          label: Für Aperogäste sichtbar,
          name: visible_apero,
          widget: boolean,
          default: true,
        }
      - {
          label: Für Festgäste sichtbar,
          name: visible_fest,
          widget: boolean,
          default: false,
        }
      - label: Bilder
        name: images
        widget: list
        fields:
          - { label: Bild, name: image, widget: image, allow_multiple: false }
