backend:
  name: github
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files: 
      - label: "Home"
        name: "home"
        file: "src/admin/content/home.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Datum, name: date, widget: date, format: DD.MM.YYYY}
          - {label: Hintergrundbild, name: background, widget: image, allow_multiple: false}
          - {label: Apéro Passwort, name: apero_pw, widget: string}
          - {label: Fest Passwort, name: fest_pw, widget: string}
  - name: gallery
    label: Galerie
    folder: src/admin/content/gallery
    create: true
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Bilder, name: images, widget: image, allow_multiple: true}