backend:
  name: github
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: Home
        name: home
        file: src/admin/content/home.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Datum, name: date, widget: date, format: DD. MMMM YYYY }
          - {
              label: Hintergrundbild,
              name: background,
              widget: image,
              allow_multiple: false,
            }
          - { label: Apéro Passwort, name: apero_pw, widget: string }
          - { label: Fest Passwort, name: fest_pw, widget: string }
      - label: "Anmeldungen"
        name: "rsvp"
        file: "src/admin/content/rsvp.md"
        fields:
          - {
              label: Apero Anmeldung Intro,
              name: apero_rsvp_intro,
              widget: markdown,
            }

          - {
              label: Fest Anmeldung Intro,
              name: fest_rsvp_intro,
              widget: markdown,
            }
          - {
              label: Text - Danke fürs ausfüllen,
              name: rsvp_sent_text,
              widget: markdown,
            }

  - name: gallery
    label: Galerie
    folder: src/admin/content/gallery
    create: true
    slug: "{{slug}}"
    extension: md
    fields:
      - { label: Name, name: title, widget: string }
      - { label: Bilder, name: images, widget: image, allow_multiple: true }
