backend:
  name: github
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files: 
      - label: "Home"
        name: "home"
        file: "src/admin/content/home.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}