backend:
  name: github
  repo: tuelsch/esra-wedding

media_folder: "static/uploads"
public_folder: "static/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    files: 
      - label: "Home"
        name: "home"
        file: "src/admin/content/home.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}